### ISSUE TITLE
Possibility of posting study mansucript as a preprint?

### ISSUE THREAD

**Issue by dhimmel** [OpenBioLink/OpenBioLink#1]
Greetings! I've been invited to review the manuscript associated with this repository for the journal _Bioinformatics_. The topic is of great interest to me, and I agree standardized benchmaking datasets for hetnet edge prediction are of critical importance for the field.

So I would love to peer review the manuscript, but I have two reservations:

1. the manuscript is not available as a preprint. Therefore, I would not be able to share my review publicly upon completing it. And of course, there's a risk the manuscript is rejected from _Bioinformatics_ and I never get to publicly share my review, causing my effort to be of only limited usefulness to the field.

2. _Bioinformatics_ is a subscription journal that paywalls access to publicly funded research. I do not want to donate my expertise towards a business model that deprives individuals access to scholarship. Now _Bioinformatics_ does have an open access for authors that are able to pay the APC. However, as a reviewer, I am not sure which option would be chosen if publication occurred.

One solution that would address both issues would be to post the manuscript as a preprint under an open license (i.e. CC BY 4.0). This way I could share my review publicly upon completing it. Furthermore, were you to not choose the OA option upon acceptance, there would be still be a route for individuals to access and reuse the fulltext.

If this solution doesn't work for you, no problem... just that I will likely decline to review (which would be a bummer). Happy to answer any questions you might have.

**Comment by matthias-samwald** [comment]
Dear @dhimmel, we have planned to submit a preprint to Arxiv and will do so very soon! I'll reply to this issue when this has been done.

I fully agree with the points you raised.

**Comment by dhimmel** [comment]
> we have planned to submit a preprint to Arxiv and will do so very soon!

Awesome! I'll go ahead and accept the review assignment.

**Comment by dhimmel** [comment]
So I accepted the review assignment, but I can't actually read the manuscript yet because the ScholarOne website is down:

> ![image](https://user-images.githubusercontent.com/1117703/70483559-2112e080-1aa6-11ea-910c-688d8536a6a6.png)

An ironic twist of fate that at the current time, the _only_ way I would be able to access the manuscript for review is via a preprint! :smirk_cat:

**Comment by matthias-samwald** [comment]
Oops, I'll hurry up then (the challenge being to de-format the neatly LaTeX-formatted, print-ready manuscript a little bit so the preprint is not equivalent to a fully formatted Bioinformatics paper...)

**Comment by matthias-samwald** [comment]
@dhimmel I have added the preprint manuscript and the supplementary file here: https://github.com/OpenBioLink/OpenBioLink/tree/master/paper

The page limit for articles of the "application notes" type is 2 pages in final formatting and the current manuscript is at the very maximum of that limit, even though it does not appear like that in the preprint.

I will update with a link to arXiv once the article gets released (probably tomorrow).

Cheers,
Matthias

**Comment by dhimmel** [comment]
For my notes, on arXiv at https://arxiv.org/abs/1912.04616v1. Thanks!

**Comment by matthias-samwald** [comment]
We have now submitted an updated version of the preprint to Arxiv.

**Comment by dhimmel** [comment]
> We have now submitted an updated version of the preprint to Arxiv.

Great! I see https://arxiv.org/abs/1912.04616v2
