### ISSUE TITLE
Generate further statistics on relations

### ISSUE THREAD

**Issue by matthias-samwald** [OpenBioLink/OpenBioLink#11]
Generate statistics on symmetric relations (relevent especially for TransE), as well as the ratio of unique (subject, predicate) and (predicate, object) pairs that are connected to more than one entity.

**Comment by LFGMUW** [comment]
[edgesCount.zip](https://github.com/OpenBioLink/OpenBioLink/files/4152818/edgesCount.zip)

**Comment by LFGMUW** [comment]
In den stats Files gibt es "Nr edges return direction" pro (Edgetype, Node1 Type, Node2 Type) Tripel. Ich soll aber zusätzlich pro (EdgeType, Node1 Instanz) und (EdgeType, Node2 Instanz) schauen pro edges file ob die Beziehung in der anderen Richtung auftritt (und zählen für wie viele es war), ja? :)

**Comment by LFGMUW** [comment]
[relationCounts.xlsx](https://github.com/OpenBioLink/OpenBioLink/files/4219017/relationCounts.xlsx)
The statistics for the first of the 4 new files -for both directions. @matthias-samwald Passt so?
