### ISSUE TITLE
Bug creating KG

### ISSUE THREAD

**Issue by ddomingof** [OpenBioLink/OpenBioLink#16]
Hi,

I got an error while creating a KG. I clicked on "select a subset of dataset" then I select CTD or another dataset and this windows shows up:

<img width="978" alt="Bildschirmfoto 2020-01-28 um 10 57 22" src="https://user-images.githubusercontent.com/15685795/73254119-19c2a600-41be-11ea-9d89-2f0bbf3ae355.png">

When I click on continue the following error appears on my terminal. Also, if you click on cancel you seem to have a bug later on because it says that the cancel action is not defined or something. So please check it out too.

```
Traceback (most recent call last):
  File
"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py",
line 1705, in __call__
    return self.func(*args)
  File
"/Users/ddomingof/PycharmProjects/OpenBioLink/src/openBioLink/gui/confirmFrame.py",
line 26, in <lambda>
    next_button = tk.Button(buttons_panel,text="Start", command=lambda:
self.controller.start(), height=1, width=15)
  File
"/Users/ddomingof/PycharmProjects/OpenBioLink/src/openBioLink/gui/gui.py",
line 92, in start
    openBioLink.main(args_list=arg_list)
  File
"/Users/ddomingof/PycharmProjects/OpenBioLink/src/openBioLink/openBioLink.py",
line 240, in main
    create_graph(args)
  File
"/Users/ddomingof/PycharmProjects/OpenBioLink/src/openBioLink/openBioLink.py",
line 44, in create_graph
    graph_creator.download_db_files()
  File
"/Users/ddomingof/PycharmProjects/OpenBioLink/src/openBioLink/graph_creation/graphCreation.py",
line 92, in download_db_files
    FileDownloader.download(db_file.url, o_file_path)
  File
"/Users/ddomingof/PycharmProjects/OpenBioLink/src/openBioLink/graph_creation/file_downloader/fileDownloader.py",
line 14, in download
    urllib.request.urlretrieve(url, o_file_path)
  File
"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py",
line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File
"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py",
line 222, in urlopen
    return opener.open(url, data, timeout)
  File
"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py",
line 525, in open
    response = self._open(req, data)
  File
"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py",
line 543, in _open
    '_open', req)
  File
"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py",
line 503, in _call_chain
    result = func(*args)
  File
"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py",
line 1347, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File
"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py",
line 1321, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname
provided, or not known>
```

**Comment by matthias-samwald** [comment]
@annabreit Any ideas? 
Potentially @nomisto could take over finalizing a fix.

**Comment by nomisto** [comment]
@annabreit I think i found the bug, gui.py line 121 always evaluates to True. Thus it is always asked if the user wants to quit, even if he has pressed cancel. I think the error occurs, if the user then presses cancel on the quit dialog.

**Comment by nomisto** [comment]
I could not reproduce the URLError though, @ddomingof do you remember which databases you selected/deselected exactly? Respectivley the settings used?

**Comment by ddomingof** [comment]
It seems I had an internet connection problem because it works now. Maybe you could try catch that to return a different message.

**Comment by ddomingof** [comment]
I will close the issue since you are aware of the button bug already. Thanks!!!

**Comment by ddomingof** [comment]
Would it be possible to print the status of the KG generation process? Because when you create a large KG and it needs time yo dont know whats happening in the middle...

**Comment by nomisto** [comment]
Thanks for you suggestions! The progress is usually written into the command line, from where you started the gui. But maybe we will provide a clear progress in the gui in the future, what would you say @annabreit ?
