### ISSUE TITLE
Creating custom graph 

### ISSUE THREAD

**Issue by 10mubeen** [OpenBioLink/OpenBioLink#18]
Hi! I'm trying to generate a graph using the GUI. Generating a default graph is done without any issues; however, when I try to create a customized graph using only a subset of source databases, I get this:

############### downloading files #################################
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.53it/s]

############### creating graph input files #################################
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  4.59it/s]

############### creating graph #################################
0it [00:00, ?it/s]
0it [00:00, ?it/s]

After several hours, I still don't see any progress and the graph files are empty. Any ideas what may be causing this?

Thanks!

**Comment by nomisto** [comment]
As i cannot recreate the problem, whould you please share what options and db you used if you can remember it? F.e. it's possible that you set maybe the quality cutoff too high.

**Comment by 10mubeen** [comment]
Thanks for getting back to me! I selected the following source databases:
- DisGeNet- gene disease
- STITCH- gene drug
- STITCH- gene drug (action)
- STITCH- gene gene
- STITCH- gene gene (action)

Quality was high and directed graph was chosen. 

This is what appears in the graph creation options on the GUI:
 -g
	 --qual hq
	 --out_format s t
	 --dbs openbiolink.graph_creation.metadata_db_file.edge.dbMetaEdgeDisGeNet.DbMetaEdgeDisGeNet openbiolink.graph_creation.metadata_db_file.edge.dbMetaEdgeStitch.DbMetaEdgeStitch openbiolink.graph_creation.metadata_db_file.edge.dbMetaEdgeStitchAction.DbMetaEdgeStitchAction openbiolink.graph_creation.metadata_db_file.edge.dbMetaEdgeString.DbMetaEdgeString openbiolink.graph_creation.metadata_db_file.edge.dbMetaEdgeStringAction.DbMetaEdgeStringAction

**Comment by annabreit** [comment]
There should have been an error message when you started, something like:

>  Due to manual exclusion of DB resources, also the edges: [...] will be removed due to deleted dependencies of used mappings (i.e. [...]) Consider manually exclude edges instead of DB resources.

 What this is trying to tell you is that for creating a graph including STRING data, also a mapping between STRING IDs and NCBI (entrez) IDs must be provided. Therefore, please also select 'Mapping - DisGeNet - Gene (string -> ncbi entrez)' as source database.
 _(there is a typo, this should be 'Mapping - STRING- Gene (string -> ncbi entrez)'_
We will try to improve the documentation and error messages more clear to avoid such problems.

**Comment by 10mubeen** [comment]
Thank you for the clarification. It's all working smoothly now!
