### ISSUE TITLE
Corrupted CSV in file DB_HPO_disease_phenotype.csv

### ISSUE THREAD

**Issue by nomisto** [OpenBioLink/OpenBioLink#19]
The created in_file DB_HPO_disease_phenotype.csv seems to have some dirty data.
In some entries multiple diseases are specified:
`"PMID:18382993;PMID:14684697;PMID:12618959;PMID:12210303";HP:0001790;PCS`
and in some appearing links:
`"http://www.ncbi.nlm.nih.gov/bookshelf/br.fcgi?book=gene&part=ofd1;ISBN-13:978-0721606156";HP:0000199;PCS`

@annabreit are you aware of this?

**Comment by annabreit** [comment]
Thanks for pointing that out! Of course, infiles should be flat and therefore multiple diseases per row should not exist. There was a mixup with the columns. Should be fixed.
