### ISSUE TITLE
Make installable with setup.py

### ISSUE THREAD

**Issue by cthoyt** [OpenBioLink/OpenBioLink#2]
It would be nice to be able to import the code with something like:

```bash
pip install openbiolink
````

then in Python:

```python
from openbiolink.evaluation.models.pykeen_models import Unstructured_PyKeen
...
```

This would also allow a lot of code cleanup since there is currently an inconsistent use of relative and absolute imports throughout the code base

**Comment by cthoyt** [comment]
Would be happy to help with a PR

**Comment by matthias-samwald** [comment]
→ Note for documentation purposes: The code has been packaged and can now be installed through pip.
