### ISSUE TITLE
Questions about edges in graphs

### ISSUE THREAD

**Issue by 10mubeen** [OpenBioLink/OpenBioLink#22]
I have a few questions about edges in the OpenBioLink graphs.

1. For the default directed graph, I have approximately 4 million edges (in the edges.csv) while in the train set file (train_sample.csv), I have around 8 million edges. What is the reason for the difference in these number of edges?

2. In the fourth column of the edge files, sometimes 1 is reported while other times there are other numbers. What do these numbers mean?

3. What is the difference between the edge types in the directed vs undirected graphs? When I compare between the edge types in the directed vs undirected edges_list.csv, I am finding the same edge types.

4. Can you direct me to where I can get more information on the edge types such as the DRUG_PREDBIND_GENE edge type?

**Comment by annabreit** [comment]
1. The edges.csv file contains all 'positive edges' of the graph (i.e. all relationships that are actually present). The train_sample.csv contains all training data for the link prediction model, consisting of both positive and negative examples.

2. The fourth column of the edges.csv indicates the quality score (i.e. the confidence of the true existence of the edge). This information is integrated from the upstream data sources, resulting in different formats (sometimes it is a number between 0 and 1, sometimes it is a string, ...) As not all data sources provide a confidence score, this column is optional.

3. The edge types themselves are the same in the directed / undirected setting. The difference is that some edge types have a directed nature (e.g. _Drug_catalysis_Gene_) while for others, the direction is not defined (e.g. _Gene_binding_Gene_). If the setting is 'undirected', in both cases, one (undirected) edge will exist for all edge types. However, if the graph should be directed, a 'true undirected' edge, e.g. _Gene_1-(Gene_binding_Gene)-Gene2_ will be translated into directed edges in both directions, i.e.  _Gene_1-(Gene_binding_Gene)->Gene2_ and _Gene_2-(Gene_binding_Gene)->Gene1_

4. We try to add the information about the edge types asap. "predbind" stands for "predicted to bind", "ptmod" for "post-translational modifications". Hope this helps for now.

We will update and expand the documentation as soon as possible to facilitate the understanding.
