### ISSUE TITLE
Issues with creation of graph

### ISSUE THREAD

**Issue by cthoyt** [OpenBioLink/OpenBioLink#24]
After running `openbiolink -p data/ -g` I got this message: 

`File does not exist: data/in_files/DB_GO_annotations.csv ! Edgetype GENE_GO will not be created`

As well as all other files seemed not to exist. Am I missing something? I would expect that without any options, it should make the full graph.

**Comment by nomisto** [comment]
Yes this is currently a little bit messy. The default values in the readme are not currently set by default, these values, as I understand it, have to still be set manually to get the default graph. Is this something you could add to the implemention of [#25 ](25)?
