### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by nomisto** [OpenBioLink/OpenBioLink#34]
The following links of databases are dead and should be replaced by the following:

Dead: http://compbio.charite.de/jenkins/job/hpo.annotations/lastSuccessfulBuild/artifact/misc/negative_phenotype_annotation.tab
Replacement: http://compbio.charite.de/jenkins/job/hpo.annotations/1269/artifact/misc/negative_phenotype_annotation.tab

Dead: http://compbio.charite.de/jenkins/job/hpo.annotations/lastSuccessfulBuild/artifact/misc/phenotype_annotation_hpoteam.tab
Replacement: http://compbio.charite.de/jenkins/job/hpo.annotations/1269/artifact/misc/phenotype_annotation_hpoteam.tab

Dead: http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/lastSuccessfulBuild/artifact/annotation/ALL_SOURCES_ALL_FREQUENCIES_genes_to_phenotype.txt
Replacement: http://compbio.charite.de/jenkins/job/hpo.annotations/lastSuccessfulBuild/artifact/util/annotation/genes_to_phenotype.txt

**Comment by nomisto** [comment]
For the other two links it was sufficient to replace lasSuccessfulBuild with the build number, that the files for our graph originally came from. 

Unfortunately this does not work for http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/lastSuccessfulBuild/artifact/annotation/ALL_SOURCES_ALL_FREQUENCIES_genes_to_phenotype.txt.

There is a new file called [genes_to_phenotype.txt](http://compbio.charite.de/jenkins/job/hpo.annotations/lastSuccessfulBuild/artifact/util/annotation/genes_to_phenotype.txt), but this file differs from the original one.

Total unique edges old: 161004
Total unique edges new: 166227

Edges contained in both files: 160518
Edges contained in old only: 485
Edges contained in new only: 5709

**Comment by sbs87** [comment]
This appears to be dead again. Just tried downloading from the latest release. The URL is not found:
http://compbio.charite.de/jenkins/job/hpo.annotations/1269/artifact/misc/phenotype_annotation_hpoteam.tab

According to the home page (http://charite.github.io/), the lab moved to new location. Wasn't able to find the HPO file, however:
https://robinsongroup.github.io/

**Comment by sbs87** [comment]
I stand corrected. I believe these are the files:
http://purl.obolibrary.org/obo/hp/hpoa/genes_to_phenotype.txt
http://purl.obolibrary.org/obo/hp/hpoa/phenotype_annotation_negated.tab
http://purl.obolibrary.org/obo/hp/hpoa/phenotype_annotation.tab

**Comment by nomisto** [comment]
Hi @sbs87 ,

Thanks for pointing this out! You are right, the links you posted are the new ones. I've updated them now.
