### ISSUE TITLE
Host benchmark files on Zenodo

### ISSUE THREAD

**Issue by matthias-samwald** [OpenBioLink/OpenBioLink#47]
(also addresses #42)

As per Charles' suggestion, we should move the benchmark files to Zenodo. Zenodo allows for more transparent versioning and long-term availability of files.
I have created a community called 'Biomedical link prediction' on Zenodo. @nomisto Please upload the latest versions of the OpenBioLink Benchmark files (including the RDF files) via https://zenodo.org/deposit/new?c=biomedical_link_prediction
and update the link on the GitHub Readme accordingly. Thanks!

**Comment by nomisto** [comment]
The files are now hosted on https://zenodo.org/record/3826919. Please verify if I filled out the metadata correctly and let me know if you want to change anyhing.

**Comment by matthias-samwald** [comment]
Looking good, thanks!
