### ISSUE TITLE
Pass val_pos_triples & val_neg_triples to the train method

### ISSUE THREAD

**Issue by robertanto** [OpenBioLink/OpenBioLink#53]
The dataset provides a pre-computed split (training, validation, testing) but there is no way to pass the validation triples to the train a custom model that may need it (as in the case of GNN).

It may be useful to add this feature to the cli.

**Comment by nomisto** [comment]
Closed with 28f500d3ef7d71ec1d231b6f4b18787e106de67b 29819cbec85dd44719432ca26a50847995d43bfb

validationset can now be passed to the train method with
```
-v for positive validation set
-nv for negative validation set
```
