### ISSUE TITLE
Add OpenBioLink to OGB

### ISSUE THREAD

**Issue by matthias-samwald** [OpenBioLink/OpenBioLink#57]
As external contribution to OGB, see https://github.com/snap-stanford/ogb/issues/1#issuecomment-706805750

**Comment by matthias-samwald** [comment]
@nomisto Was there any feedback so far?

**Comment by nomisto** [comment]
@matthias-samwald Yes unfortunately they decided that are not able to include our dataset, since they already have a biomedical knowledge graph.
