### ISSUE TITLE
Release the OpenBioLink software under an open source license

### ISSUE THREAD

**Issue by dhimmel** [OpenBioLink/OpenBioLink#6]
The paper mentions that a good benchmark dataset should have:

> Open-source code for evaluation (independent of model)

However, this codebase is not released under an [open source software license](https://opensource.org/licenses).

Personally, I'd recommend a permissive and simple license like MIT, BSD 3-Clause, or [Blue Oak](https://blueoakcouncil.org/license/1.0.0).

This can be separate from the license applied to dataset that we discuss in #5.

**Comment by matthias-samwald** [comment]
@annabreit I suggest using the MIT license

**Comment by matthias-samwald** [comment]
The code has now been released under the MIT license.
