### ISSUE TITLE
Add OpenBioLink to Benchmarking GNNs?

### ISSUE THREAD

**Issue by fmellomascarenhas** [OpenBioLink/OpenBioLink#61]
Hi all, not sure if this is possible, but you guys might be interested in checking it

https://github.com/graphdeeplearning/benchmarking-gnns

**Comment by matthias-samwald** [comment]
@nomisto The repository describes new dataset addition procedures here: https://github.com/graphdeeplearning/benchmarking-gnns/blob/master/docs/04_add_dataset.md -- how difficult would this be?

@nomisto Maybe also ask the maintainers of that project first if they would want to officially add OBL to their project. I think only then it would make sense for us to invest effort.
