### ISSUE TITLE
Does it make sense to combine assessment of edge prediction across all edge types?

### ISSUE THREAD

**Issue by dhimmel** [OpenBioLink/OpenBioLink#8]
The manuscript mentions:

> For evaluation, a wide range of metrics is offered, such as hits@k, mean reciprocal rank (MRR), area under the receiver operator characteristic curve (ROC AUC) and area under the precision-recall curve (PR AUC).

And later states:

> The best results with hits@10 of 7.5% was achieved by a TransE model with an embedding dimensionality of 100.

So it reads like the metrics to evaluate performance combine performance across all edge types? How does this work, since each edge type has a difference prevalence of positives and a different number of possible edges? How do you avoid having a few edge types monopolize the metric?

**Comment by matthias-samwald** [comment]
TODO: Add information on performance per edge type to manuscript supplementary information.

**Comment by matthias-samwald** [comment]
@annabreit What's the status of the per-relation evaluation?

**Comment by matthias-samwald** [comment]
→  Per-relation evaluation results have been added to the supplementary material (Table S5), the manuscript has been updated to refer to the supplementary material.

**Comment by dhimmel** [comment]
Great! Looks like the [`supplementary data.pdf`](https://github.com/OpenBioLink/OpenBioLink/blob/5481448875b5bf0a9d6a2bdddb0d6d761ba2a19b/paper/supplementary%20data.pdf) on github still needs to be updated to contain Table S5. I do see the table in the Supplemantary Data for the _Bioinformatics_ resubmission.
